name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main # Altere para a branch desejada

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Passo 1: Checkout do código
    - name: Checkout repository
      uses: actions/checkout@v3

    # Passo 2: Configure o Google Cloud SDK
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.moto-academy-web }}

    # Passo 3: Faça o build da imagem Docker
    - name: Build Docker image
      run: |
        IMAGE_NAME=gcr.io/${{ secrets.moto-academy-web }}/node-cloud-sql
        docker build -t $IMAGE_NAME .
        echo "::set-output name=image::$IMAGE_NAME"

    # Passo 4: Autentique o Docker no GCR
    - name: Authenticate Docker to Google Cloud Registry
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" | docker login -u _json_key --password-stdin https://gcr.io

    # Passo 5: Publique a imagem no GCR
    - name: Push Docker image to Google Container Registry
      run: |
        IMAGE_NAME=gcr.io/${{ secrets.moto-academy-web }}/node-cloud-sql
        docker push $IMAGE_NAME

    # Passo 6: Faça o deploy para o Cloud Run
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy node-cloud-sql \
          --image gcr.io/${{ secrets.moto-academy-web }}/node-cloud-sql \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --add-cloudsql-instances moto-academy-web:us-central1:euclideslins
